const canvas = document.getElementById('probCanvas');
const frame = document.getElementById('canvasFrame');
const context = canvas.getContext('2d');
const elements = {
  streamBadge: document.getElementById('streamBadge'), seedBadge: document.getElementById('seedBadge'),
  uniqueValue: document.getElementById('uniqueValue'), estimateValue: document.getElementById('estimateValue'),
  hllErrorValue: document.getElementById('hllErrorValue'), fillValue: document.getElementById('fillValue'),
  falsePositiveValue: document.getElementById('falsePositiveValue'), memoryValue: document.getElementById('memoryValue'),
  benchmarkValue: document.getElementById('benchmarkValue'), statusValue: document.getElementById('statusValue'),
  countRange: document.getElementById('countRange'), bloomRange: document.getElementById('bloomRange'), precisionRange: document.getElementById('precisionRange'),
  countValue: document.getElementById('countValue'), bloomValue: document.getElementById('bloomValue'), precisionValue: document.getElementById('precisionValue'),
  runButton: document.getElementById('runButton'), benchmarkButton: document.getElementById('benchmarkButton'), seedButton: document.getElementById('seedButton'),
  pngButton: document.getElementById('pngButton'), jsonButton: document.getElementById('jsonButton'), reportButton: document.getElementById('reportButton'),
};
const state = { seed: 23, result: null, benchmark: null };
function settings(){return{count:Number(elements.countRange.value),bloomSize:Number(elements.bloomRange.value),precision:Number(elements.precisionRange.value),seed:state.seed};}
function labels(){const s=settings();elements.countValue.textContent=s.count;elements.bloomValue.textContent=s.bloomSize;elements.precisionValue.textContent=s.precision;elements.seedBadge.textContent=`Seed ${s.seed}`;}
function resizeCanvas(){const r=frame.getBoundingClientRect();const w=Math.max(720,Math.floor(r.width));const h=Math.max(420,Math.floor(r.height));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;draw();}}
function analyze(){labels();state.result=ProbCore.analyze(settings());update();draw();}
function draw(){const g=context.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,'#080b12');g.addColorStop(1,'#141821');context.fillStyle=g;context.fillRect(0,0,canvas.width,canvas.height);if(!state.result)return;drawBloom();drawRegisters();}
function drawBloom(){const bits=state.result.bloom.bits;const cols=128;const rows=Math.ceil(bits.length/cols);const left=24,top=50,w=(canvas.width*.54)/cols,h=(canvas.height*.52)/rows;for(let i=0;i<bits.length;i+=1){context.fillStyle=bits[i]?'#7dd3fc':'rgba(125,211,252,.08)';context.fillRect(left+(i%cols)*w,top+Math.floor(i/cols)*h,Math.max(1,w-.5),Math.max(1,h-.5));}context.fillStyle='#c8d2df';context.font='800 12px ui-monospace,Consolas,monospace';context.fillText('bloom bitset',left,top-14);}
function drawRegisters(){const regs=state.result.hll.registers;const left=canvas.width*.64,top=70,width=canvas.width*.3,height=canvas.height*.48;const max=Math.max(...regs,1);regs.forEach((value,index)=>{const bw=width/regs.length;const bh=value/max*height;context.fillStyle='#ffde43';context.fillRect(left+index*bw,top+height-bh,Math.max(1,bw-1),bh);});context.strokeStyle='rgba(255,222,67,.25)';context.strokeRect(left,top,width,height);context.fillStyle='#c8d2df';context.font='800 12px ui-monospace,Consolas,monospace';context.fillText('hyperloglog registers',left,top-14);}
function update(){const m=state.result.metrics;elements.uniqueValue.textContent=String(m.uniqueCount);elements.estimateValue.textContent=String(Math.round(m.hllEstimate));elements.hllErrorValue.textContent=`${(m.hllError*100).toFixed(1)}%`;elements.fillValue.textContent=`${Math.round(m.bloomFill*100)}%`;elements.falsePositiveValue.textContent=`${(m.falsePositiveRate*100).toFixed(2)}%`;elements.memoryValue.textContent=`${m.memoryBytes} B`;elements.streamBadge.textContent=`${m.streamCount} items`;elements.statusValue.textContent='Analyzed';}
function bench(){const started=performance.now();state.benchmark=ProbCore.benchmarkAnalyze({...settings(),iterations:10});state.benchmark.averageMs=(performance.now()-started)/state.benchmark.iterations;elements.benchmarkValue.textContent=`${state.benchmark.averageMs.toFixed(1)} ms`;}
function meta(){return{project:'023 - Probabilistic Data Lab',exportedAt:new Date().toISOString(),settings:settings(),metrics:state.result&&state.result.metrics,benchmark:state.benchmark};}
function download(n,t,text){const u=URL.createObjectURL(new Blob([text],{type:t}));const a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u);}
function report(){const m=state.result.metrics;const text=`# 023 - Probabilistic Data Lab\nUnique: ${m.uniqueCount}\nHLL estimate: ${m.hllEstimate.toFixed(1)}\nHLL error: ${(m.hllError*100).toFixed(2)}%\nFalse positives: ${(m.falsePositiveRate*100).toFixed(2)}%\n`;if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>{elements.statusValue.textContent='Report copied';});else download('prob-report.md','text/markdown',text);}
[elements.countRange,elements.bloomRange,elements.precisionRange].forEach((e)=>{e.addEventListener('input',analyze);e.addEventListener('change',analyze);});elements.runButton.addEventListener('click',analyze);elements.benchmarkButton.addEventListener('click',bench);elements.seedButton.addEventListener('click',()=>{state.seed=(state.seed*1664525+1013904223)>>>0;analyze();});elements.pngButton.addEventListener('click',()=>{const a=document.createElement('a');a.download='probabilistic-data-lab.png';a.href=canvas.toDataURL('image/png');a.click();});elements.jsonButton.addEventListener('click',()=>download('probabilistic-data-lab.json','application/json',`${JSON.stringify(meta(),null,2)}\n`));elements.reportButton.addEventListener('click',report);window.addEventListener('resize',resizeCanvas);resizeCanvas();analyze();
