const canvas = document.getElementById('sudokuCanvas');
const frame = document.getElementById('canvasFrame');
const context = canvas.getContext('2d');
const elements = {
  presetBadge: document.getElementById('presetBadge'), solvedBadge: document.getElementById('solvedBadge'),
  givenValue: document.getElementById('givenValue'), candidateValue: document.getElementById('candidateValue'), decisionValue: document.getElementById('decisionValue'),
  backtrackValue: document.getElementById('backtrackValue'), depthValue: document.getElementById('depthValue'), rowValue: document.getElementById('rowValue'),
  benchmarkValue: document.getElementById('benchmarkValue'), statusValue: document.getElementById('statusValue'), presetSelect: document.getElementById('presetSelect'),
  solveButton: document.getElementById('solveButton'), benchmarkButton: document.getElementById('benchmarkButton'), pngButton: document.getElementById('pngButton'),
  jsonButton: document.getElementById('jsonButton'), reportButton: document.getElementById('reportButton'),
};
const state = { result: null, benchmark: null };
function resizeCanvas(){const r=frame.getBoundingClientRect();const w=Math.max(720,Math.floor(r.width));const h=Math.max(420,Math.floor(r.height));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;draw();}}
function solve(){state.result=ExactCore.solvePuzzle(elements.presetSelect.value);update();draw();}
function draw(){const g=context.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,'#0b0d12');g.addColorStop(1,'#171821');context.fillStyle=g;context.fillRect(0,0,canvas.width,canvas.height);if(!state.result)return;const size=Math.min(canvas.width,canvas.height)*.72;const left=(canvas.width-size)*.5;const top=(canvas.height-size)*.5;const cell=size/9;context.fillStyle='rgba(255,255,255,.03)';context.fillRect(left,top,size,size);for(let i=0;i<=9;i+=1){context.strokeStyle=i%3===0?'#ffde43':'rgba(255,255,255,.22)';context.lineWidth=i%3===0?3:1;context.beginPath();context.moveTo(left+i*cell,top);context.lineTo(left+i*cell,top+size);context.moveTo(left,top+i*cell);context.lineTo(left+size,top+i*cell);context.stroke();}context.font=`${cell*.56}px ui-sans-serif,system-ui`;context.textAlign='center';context.textBaseline='middle';state.result.board.forEach((value,index)=>{const given=state.result.puzzle[index]!==0;context.fillStyle=given?'#ffde43':'#74f2ce';context.fillText(String(value||''),left+(index%9)*cell+cell*.5,top+Math.floor(index/9)*cell+cell*.52);});}
function update(){const s=state.result.stats;elements.givenValue.textContent=String(s.givens);elements.candidateValue.textContent=String(state.result.candidates);elements.decisionValue.textContent=String(s.decisions);elements.backtrackValue.textContent=String(s.backtracks);elements.depthValue.textContent=String(s.maxDepth);elements.rowValue.textContent=String(s.solutionRows);elements.presetBadge.textContent=elements.presetSelect.options[elements.presetSelect.selectedIndex].textContent;elements.solvedBadge.textContent=state.result.solved?'Solved':'Failed';elements.statusValue.textContent=state.result.solved?'Solved':'Failed';}
function bench(){const started=performance.now();state.benchmark=ExactCore.benchmarkSolve({preset:elements.presetSelect.value,iterations:16});state.benchmark.averageMs=(performance.now()-started)/state.benchmark.iterations;elements.benchmarkValue.textContent=`${state.benchmark.averageMs.toFixed(2)} ms`;}
function meta(){return{project:'024 - Exact Cover Sudoku',exportedAt:new Date().toISOString(),preset:elements.presetSelect.value,stats:state.result&&state.result.stats,solved:state.result&&state.result.solved,benchmark:state.benchmark};}
function download(n,t,text){const u=URL.createObjectURL(new Blob([text],{type:t}));const a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u);}
function report(){const s=state.result.stats;const text=`# 024 - Exact Cover Sudoku\nSolved: ${state.result.solved}\nGivens: ${s.givens}\nCandidates: ${state.result.candidates}\nDecisions: ${s.decisions}\nBacktracks: ${s.backtracks}\n`;if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>{elements.statusValue.textContent='Report copied';});else download('exact-cover-report.md','text/markdown',text);}
elements.presetSelect.addEventListener('change',solve);elements.solveButton.addEventListener('click',solve);elements.benchmarkButton.addEventListener('click',bench);elements.pngButton.addEventListener('click',()=>{const a=document.createElement('a');a.download='exact-cover-sudoku.png';a.href=canvas.toDataURL('image/png');a.click();});elements.jsonButton.addEventListener('click',()=>download('exact-cover-sudoku.json','application/json',`${JSON.stringify(meta(),null,2)}\n`));elements.reportButton.addEventListener('click',report);window.addEventListener('resize',resizeCanvas);resizeCanvas();solve();
